version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: monthly
  groups:
    minor-actions-dependencies:
      # GitHub Actions: Only group minor and patch updates (we want to carefully review major updates)
      update-types: [ minor, patch ]

- package-ecosystem: maven
  directories: [ "**/*" ]
  schedule:
    interval: monthly
  ignore:
    # Only patch updates don't require coordination with the deployed database
    - dependency-name: "org.foundationdb:fdb-java"
      update-types:
        - version-update:semver-major
        - version-update:semver-minor
    #  https://github.com/dropwizard/dropwizard/pull/11273
    - dependency-name: "ch.qos.logback:*"
      versions: [">=1.6.0"]
    # this dependency monitors convergence conflicts, so we pin a specific version
    - dependency-name: "tools.jackson.core:jackson-databind"
    # this dependency monitors convergence conflicts, so we pin a specific version
    - dependency-name: "com.squareup.okio:okio-jvm"
    # https://github.com/jetty/jetty.project/issues/15657
    - dependency-name: "org.eclipse.jetty:*"
      versions: ["<=12.1.12"]

  groups:
    minor-java-dependencies:
      # Java: Only group minor and patch updates (we want to carefully review major updates)
      update-types: [ minor, patch ]

