name: CI Build and Run Signal-Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '21'

    - name: Clone Signal-Server repository
      run: |
        git clone https://github.com/offsoc/Signal-Server.git
        cd Signal-Server

    - name: Go offline with Maven dependencies
      run: |
        cd Signal-Server
        ./mvnw dependency:go-offline

    - name: Clean and install without tests
      run: |
        cd Signal-Server
        ./mvnw clean install -DskipTests -Pexclude-spam-filter
        
    - name: Upload compiled artifacts
      uses: actions/upload-artifact@v3
      with:
        name: signal-server-artifacts
        path: Signal-Server/service/target/*.jar 
    - name: Upload compiled artifacts
      uses: actions/upload-artifact@v3
      with:
        name: websocket-resources-artifacts
        path: Signal-Server/websocket-resources/target/*.jar 

    - name: Upload compiled artifacts
      uses: actions/upload-artifact@v3
      with:
        name:  api-doc-artifacts
        path: Signal-Server/api-doc/target/*.jar 

    - name: Upload compiled artifacts
      uses: actions/upload-artifact@v3
      with:
        name:  integration-tests-artifacts
        path: Signal-Server/integration-tests/target/*.jar 


  
