name: Build Signal Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Install Maven
        run: sudo apt-get install -y maven

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: signal-server-artifact
          path: target/signal-server.jar
